image: ghcr.io/jethome-homeassistant/{arch}-homeassistant-base
build_from:
  aarch64: ghcr.io/jethome-homeassistant/aarch64-base-python:3.13-alpine3.22-2025.11.1
  armhf: ghcr.io/jethome-homeassistant/armhf-base-python:3.13-alpine3.22-2025.11.1
  armv7: ghcr.io/jethome-homeassistant/armv7-base-python:3.13-alpine3.22-2025.11.1
  amd64: ghcr.io/jethome-homeassistant/amd64-base-python:3.13-alpine3.22-2025.11.1
  i386: ghcr.io/jethome-homeassistant/i386-base-python:3.13-alpine3.22-2025.11.1
cosign:
  base_identity: https://github.com/jethome-homeassistant/docker-base/.*
  identity: https://github.com/jethome-homeassistant/docker/.*
labels:
  io.hass.type: homeassistant-base
  org.opencontainers.image.title: JH Home Assistant Core baseimage
  org.opencontainers.image.description: Baseimage for Home Assistant Core container/supervisor installation
  org.opencontainers.image.source: https://github.com/jethome-homeassistant/docker
  org.opencontainers.image.authors: The Home Assistant Authors (JetHome patched)
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
args:
  SSOCR_VERSION: 2.25.1
  LIBCEC_VERSION: 6.0.2
  TELLDUS_COMMIT: 2598bbed16ffd701f2a07c99582f057a3decbaf3
  PICOTTS_HASH: e3ba46009ee868911fa0b53db672a55f9cc13b1c
