name: JH Build base images

on:
  pull_request:
    branches: ["master-jethub"]
  release:
    types: ["published"]

env:
  BUILD_TYPE: base

jobs:
  init:
    name: Initialize build
    runs-on: ${{ vars.RUNNER }}
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0

    - name: Get information
      id: info
      uses: jethome-homeassistant/actions/helpers/info@master-jethub

    - name: Get version
      id: version
      uses: jethome-homeassistant/actions/helpers/version@master-jethub
      with:
        type: ${{ env.BUILD_TYPE }}

  build:
    name: Build ${{ matrix.arch }} base image
    needs: init
    runs-on: ${{ vars.RUNNER }}
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v5.0.0

    - name: Check if requirements files changed
      uses: tj-actions/changed-files@v47
      id: requirements
      with:
          files: requirements.txt

    - name: Build wheels cp313
      uses: jethome-homeassistant/wheels@2025.09.1
      if: github.event_name == 'release' || steps.requirements.outputs.any_changed == 'true'
      with:
        tag: musllinux_1_2
        abi: cp313
        arch: ${{ matrix.arch }}
        wheels-key: ${{ secrets.WHEELS_KEY }}
        apk: "mariadb-dev;postgresql-dev;libffi-dev"
        requirements: "requirements.txt"

    - name: Login to GitHub Container Registry
      if: github.event_name == 'release'
      uses: docker/login-action@v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set build arguments
      if: github.event_name != 'release'
      run: echo "BUILD_ARGS=--test" >> $GITHUB_ENV

    - name: Build base image
      uses: jethome-homeassistant/builder@2025.09.0
      with:
        args: |
          $BUILD_ARGS \
          --${{ matrix.arch }} \
          --target /data \
          --cosign \
          --generic ${{ needs.init.outputs.version }}
